// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://mlykbkaebrmymdildcwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1seWtia2FlYnJteW1kaWxkY3dnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0OTUwODAsImV4cCI6MjA3MDA3MTA4MH0.Wi6Np6z9AWUIJbRxM4Nl5xLx4EDVa2kCJlurhKl_dhk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);