// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ilbfogxlhrzdcqkwtlyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsYmZvZ3hsaHJ6ZGNxa3d0bHlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTM2MTksImV4cCI6MjA2OTk4OTYxOX0.ldYrIgOtewuRNvn8Af8sq7mPRIdMEr0aOCT_2pNLAsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);